### ISSUE TITLE
Question about card metadata

### ISSUE THREAD

**Issue by golyalpha** [cfpwastaken/create-cards#2]
Hi, I just tried out your mod and wanted to combine it with the Vendor block from Create: Numismatics, but I ran into an issue - for some reason, the Vendor block wouldn't take the tickets as stock.

Later I noticed that in the metadata of each ticket, there's an owner part, and the display and content parts - which all match every ticket, but then there's also an id part which seems to be random for every ticket made. 

I suspect that difference in metadata is why the Vendor block will refuse to take the ticket as stock (it only allows the same item as in the display slot in its inventory), so I was curious, why is that ID included? The card reader doesn't seem to really do anything with it as it'll happily take all the tickets.

PS: I'm actually really confused rn as I've read some of the code and I feel like the mod on Modrinth works nothing like the code I've seen...

**Comment by cfpwastaken** [comment]
I see. The ID metadata is a remnant from dev, the card readers used to only accept the cards with some exact ID. I later changed this, but the id is still there.
I'll remove it, but I don't think i can retroactively remove the ID from your tickets when they already have them.

**Comment by cfpwastaken** [comment]
New Cards and Tickets are no longer created with an ID attribute in version 1.1.
