### ISSUE TITLE
Compatability with Fabric Loader version 0.15.9

### ISSUE THREAD

**Issue by axotailyn** [cfpwastaken/create-cards#3]
hello, i wanted to play with this mod on my server with friends but server crashes on launch and says it requires loader version 0.15.10, i would update it but cannot due to fear of our modpack suddenly breaking and not start up, would this be possible?

**Comment by cfpwastaken** [comment]
.9 to .10 is just a minor version update. Minor versions don't break anything. Please just try updating to 0.15.10 and see if it works.

**Comment by axotailyn** [comment]
> .9 to .10 is just a minor version update. Minor versions don't break anything. Please just try updating to 0.15.10 and see if it works.

i updated it and all worked fine, sorry to open this issue without trying before! love the mod keep up the good work :)
